### ISSUE TITLE
Mention size-structured plankton inputs in the Readme?

### ISSUE THREAD

**Issue by juliablanchard** [sizespectrum/therMizer#2]
Hi Phoebe & Romain - exciting to see this package coming together! Just a thought:  probably worth highlighting that thermizer isn't only for simulating changes in temperature in mizer but also - and importantly - changes in the resource size spectra (particularly plankton as currently set up). This is an important feature of marine ecosystem climate impact projections and how thermizer is used in practice, which could be overlooked if not directly stated in the README.

**Comment by pwoodworth-jefcoats** [comment]
Thanks for catching this!  I'll add in some text and example code in the README.

**Comment by pwoodworth-jefcoats** [comment]
I added some explanatory text about this to the README.  I'd like to include an example, too, and am thinking about the most straightforward way to do this.  Maybe constructing a spectrum from a slope, intercept, and size range, and then adding random variation over time?  Other ideas welcome!

**Comment by pwoodworth-jefcoats** [comment]
I added in an example of creating an n_pp_array.  It's very generic, though.  Just let me know if you had something different in mind.
